version: '3'
services:
    web:
        build: ./web
        volumes:
            - ./web/public:/var/www/html
            - ./web/craft:/var/www/craft
        depends_on:
            - db
        ports:
            - "8080:80"
    assets:
        build: ./assets
        ports:
            - "35729:35729"
        volumes:
            - ./assets/gulpfile.js:/assets/gulpfile.js:ro
            - ./web/public/static/styles:/assets/styles:ro
            - ./web/public/static/scripts:/assets/scripts:ro
            - ./web/public/static/build:/assets/build
    db:
        image: mariadb:5.5
        ports:
            - "3380:3306"
        environment:
            MYSQL_PASSWORD: docker
            MYSQL_ROOT_PASSWORD: docker
            MYSQL_USER: docker
            MYSQL_DATABASE: craftcms
